apiVersion: v1
kind: Pod
metadata:
  name: search
  namespace: ors
  labels:
    app: search
spec:
  containers:
  - name: search
    imagePullPolicy: Always
    image: jniestroy/search
    env:
      - name: STARDOG_USERNAME
        value: username
      - name: STARDOG_URL
        value: http://stardog:5820/
      - name: STARDOG_PASSWORD
        value: password
      - name: PYTHONUNBUFFERED
        value: "0"
      - name: ORS_URL
        value: http://mds.ors/
    command:
        - python3
        - search.py
